version: 2.1
jobs:
  docker_compose:
    working_directory: ~/archivesspace-development
    docker:
      - image: circleci/openjdk:11-jdk-buster-node-browsers-legacy
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          key: circleci-archivesspace-development
      - run:
          name: Retrieve the archivesspace source code
          command: |
            if [[ ! -d archivesspace ]]; then
              git clone https://github.com/archivesspace/archivesspace.git
            fi
      - run:
          name: Lint the Docker Compose configuration
          command: docker-compose config
      - save_cache:
          paths:
            - ~/archivesspace-development
          key: circleci-archivesspace-development

workflows:
  docker:
    jobs:
      - docker_compose
